const icons = {
  play: "ph:play-fill",
  audio: "ic:round-audio-file",
  error: "subway:error",
  menu: "mingcute:menu-fill",
  pause: "ph:pause-fill",
  download: "material-symbols:download",
  save: "material-symbols:save",
  heart: "mdi:heart",
  restart: "ph:skip-back-fill",
  volumeHigh: "ph:speaker-simple-high-fill",
  volumeMid: "ph:speaker-simple-low-fill",
  volumeLow: "ph:speaker-simple-none-fill",
  volumeMute: "ph:speaker-simple-none-fill",
  check: "fa-solid:check",
  trash: "mdi:trash",
  edit: "bxs:edit",
  settings: "codicon:settings",
  back: "ion:arrow-back-circle",
  left: "icon-park-outline:left",
  right: "icon-park-outline:right",
  lab: "raphael:lab",
  waveform: "bi:soundwave",
  processing: "eos-icons:bubble-loading",
};

export default icons;
